CREATE DATABASE exercises2_3;
USE exercises2_3;

CREATE TABLE VatTu(
 maVT INT PRIMARY KEY AUTO_INCREMENT,
 tenVT VARCHAR(255) NOT NULL
);

CREATE TABLE DonDatHang(
 soDH INT PRIMARY KEY AUTO_INCREMENT,
 maNCC INT,
 ngayDH DATETIME
);
 CREATE TABLE ChiTietDonDatHang(
 FOREIGN KEY (maVT) REFERENCES VatTu(maVT),
 FOREIGN KEY (soDH) REFERENCES DonDatHang(soDH)
 );

CREATE TABLE NhaCungCap(
 FOREIGN KEY (maNCC) REFERENCES DonDatHang(maNCC),
 tenNCC VARCHAR(255) NOT NULL,
 diaChi VARCHAR(255) NOT NULL,
 soDienThoai VARCHAR(11) NOT NULL
);

CREATE TABLE PhieuXuat(
 soPx INT PRIMARY KEY AUTO_INCREMENT,
 ngayXuat DATETIME
);

CREATE TABLE PhieuXuatChiTiet(
 FOREIGN KEY( soPX) REFERENCES PhieuXuat(soPx),
 FOREIGN KEY(maVT) REFERENCES VatTu(maVT),
 donGiaXuat DOUBLE,
 soLuongXuat INT
);

CREATE TABLE PhieuNhap(
 soPn INT PRIMARY KEY AUTO_INCREMENT,
 ngayNhap DATETIME
);

CREATE TABLE PhieuNhapChiTiet(
 FOREIGN KEY (soPn) REFERENCES PhieuNhap(soPn),
 FOREIGN KEY (maVT) REFERENCES VatTu(maVT),
 donGiaNhap DOUBLE,
 soLuongNhap INT
);